varnish:
    build: ./varnish
    ports:
        - "5000:80"
    links:
        - web:backend-host
    environment:
        VCL_CONFIG: /etc/varnish/default.vcl
        CACHE_SIZE: 64m
        VARNISHD_PARAMS: -p default_ttl=3600 -p default_grace=3600
web:
    build: ./web
    ports:
        - "5001:80"
    volumes:
        - ..:/srv/www/code
    links:
        - datamysql
datamysql:
    image: mysql:5.6
    volumes:
        - /tmp/data/mysql:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: admin-password
        MYSQL_DATABASE: dev-db
        MYSQL_USER: dev-user
        MYSQL_PASSWORD: dev-pw
test:
    build: ./web
    volumes:
        - ..:/srv/www/code
    links:
        - web
    command: make test
